PRAGMA foreign_keys=OFF;

BEGIN TRANSACTION;

CREATE TABLE "Socis" ( "Codi" INTEGER PRIMARY KEY, "DataAlta" TEXT NOT NULL, "DNI" TEXT NOT NULL, "Nom" TEXT NOT NULL, "Cognom1" TEXT, "Cognom2" TEXT, "Adreça" TEXT, "Telefon" TEXT, "CodiPostal" TEXT, "Poblacio" TEXT, "Email" TEXT, "Pagat" INTEGER NOT NULL);

CREATE TABLE "Cannabis" ( "Id" INTEGER PRIMARY KEY AUTOINCREMENT, "CodiSoci" INTEGER NOT NULL, "Data" TEXT NOT NULL, "IdPot" INTEGER NOT NULL, "Grams" INTEGER NOT NULL, "Preu" REAL NOT NULL);

CREATE TABLE "Pots" ( "Id" INTEGER PRIMARY KEY AUTOINCREMENT, "Num" INTEGER NOT NULL, "Grams" INTEGER NOT NULL);

CREATE TABLE "Altres" ( "Id" INTEGER PRIMARY KEY AUTOINCREMENT, "Data" TEXT NOT NULL, "Diners" REAL NOT NULL);

COMMIT;
